import { DEFAULT_SETTINGS, type GenerationSettings, type ScanResult } from "../types.js";
import type { TemplateAdditions } from "../templates/types.js";

function getSdkInstallBlock(stack: string, version?: string): string {
  switch (stack) {
    case "dotnet":
      return `
######################
# .NET SDK ${version ?? "8.0"}
######################

RUN apt-get update && apt-get install -y --no-install-recommends \\
    wget apt-transport-https \\
  && wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh \\
  && chmod +x /tmp/dotnet-install.sh \\
  && /tmp/dotnet-install.sh --channel ${version ?? "8.0"} --install-dir /usr/share/dotnet \\
  && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \\
  && rm /tmp/dotnet-install.sh \\
  && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV DOTNET_ROOT=/usr/share/dotnet`;

    case "node": {
      const v = version ?? "20";
      return `
######################
# Node.js ${v}.x
######################

RUN curl -fsSL https://deb.nodesource.com/setup_${v}.x | bash - \\
  && apt-get install -y nodejs \\
  && apt-get clean && rm -rf /var/lib/apt/lists/*`;
    }

    case "python":
      return `
######################
# Python 3
######################

RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3 python3-pip python3-venv \\
  && apt-get clean && rm -rf /var/lib/apt/lists/*`;

    case "rust":
      return `
######################
# Rust
######################

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/home/\${USERNAME}/.cargo/bin:\${PATH}"`;

    case "go": {
      const goVer = version ?? "1.22";
      return `
######################
# Go ${goVer}
######################

RUN wget -q https://go.dev/dl/go${goVer}.0.linux-amd64.tar.gz -O /tmp/go.tar.gz \\
  && tar -C /usr/local -xzf /tmp/go.tar.gz \\
  && rm /tmp/go.tar.gz
ENV PATH="/usr/local/go/bin:\${PATH}"`;
    }

    case "ruby":
      return `
######################
# Ruby
######################

RUN apt-get update && apt-get install -y --no-install-recommends \\
    ruby-full build-essential \\
  && apt-get clean && rm -rf /var/lib/apt/lists/*`;

    case "java":
      return `
######################
# Java 21
######################

RUN apt-get update && apt-get install -y --no-install-recommends \\
    openjdk-21-jdk-headless \\
  && apt-get clean && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64`;

    default:
      return "";
  }
}

export function generateDockerfile(
  scan: ScanResult,
  templateAdditions?: TemplateAdditions,
  settings: GenerationSettings = DEFAULT_SETTINGS
): string {
  const sdkBlocks = scan.stacks
    .map((s) => getSdkInstallBlock(s.name, s.version))
    .filter(Boolean);

  const templateBlocks = templateAdditions?.dockerfileSteps.join("\n") ?? "";

  return `# syntax=docker/dockerfile:1.4
# Generated by devcontainer-init
FROM debian:bookworm-slim

######################
# Build ARGs
######################

ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=\${USER_UID}
ARG WORKSPACE_DIR=/workspaces/${scan.projectName}
# IANA timezone; override via build.args in devcontainer.json.
ARG TZ=${settings.timezone}
# Build-only: keeps tzdata from prompting during the package install below.
ARG DEBIAN_FRONTEND=noninteractive

######################
# Environment
######################

ENV TZ=\${TZ}
ENV SHELL=/bin/bash
ENV HOME="/home/\${USERNAME}"
ENV DEVCONTAINER=true

######################
# System Packages
######################

RUN apt-get update && apt-get install -y --no-install-recommends \\
  git \\
  curl \\
  wget \\
  ca-certificates \\
  gnupg2 \\
  sudo \\
  jq \\
  bc \\
  less \\
  procps \\
  nano \\
  vim \\
  unzip \\
  bash \\
  bash-completion \\
  tzdata \\
  && ln -snf /usr/share/zoneinfo/\${TZ} /etc/localtime \\
  && echo "\${TZ}" > /etc/timezone \\
  && dpkg-reconfigure -f noninteractive tzdata \\
  && apt-get clean && rm -rf /var/lib/apt/lists/*
${sdkBlocks.join("\n")}

######################
# User Setup
######################

RUN groupadd --gid \${USER_GID} \${USERNAME} 2>/dev/null || true \\
  && useradd --uid \${USER_UID} --gid \${USER_GID} -m -s /bin/bash \${USERNAME} 2>/dev/null || true \\
  && echo "\${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/\${USERNAME} \\
  && chmod 0440 /etc/sudoers.d/\${USERNAME}

######################
# Workspace
######################

RUN mkdir -p \${WORKSPACE_DIR} && chown -R \${USER_UID}:\${USER_GID} \${WORKSPACE_DIR}
WORKDIR \${WORKSPACE_DIR}
${templateBlocks}
`;
}
